name = "prompt-producer"
main = "dist/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:worker"

[vars]
NODE_ENV = "production"

# Add environment variables here
# DATABASE_URL will be set as a secret
# SESSION_SECRET will be set as a secret
# NEWS_API_KEY will be set as a secret

[[kv_namespaces]]
binding = "PROMPT_PRODUCER_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# For local development
[env.dev]
name = "prompt-producer-dev"
vars = { NODE_ENV = "development" }

# For production
[env.production]
name = "prompt-producer-prod"
vars = { NODE_ENV = "production" }