name = "prompt-producer-prod"
main = "dist/spa-worker.js"
compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist/public"

[build]
command = "npm run build:all"

[vars]
NODE_ENV = "production"

[observability.logs]
enabled = true

# Environment variables are configured as secrets using:
# wrangler secret put DATABASE_URL
# wrangler secret put SESSION_SECRET  
# wrangler secret put NEWS_API_KEY
# wrangler secret put ISSUER_URL
# wrangler secret put REPL_ID
# wrangler secret put REPLIT_DOMAINS

# These secrets will be available as env.DATABASE_URL, env.SESSION_SECRET, etc. in the worker

# Custom domain routes
routes = [
  { pattern = "promptproducer.me/*", zone_name = "promptproducer.me" },
  { pattern = "www.promptproducer.me/*", zone_name = "promptproducer.me" }
]

[[d1_databases]]
binding = "DB"
database_name = "prompt-producer-db"
database_id = "25529814-a997-41b9-95d3-ecb453f49fbf"

[[kv_namespaces]]
binding = "PROMPT_PRODUCER_KV"
id = "563c2211b8144bf29c2367309174dbe6"
preview_id = "386404046e2548ff8d7208062c14fa5a"

# For local development
[env.dev]
name = "prompt-producer-dev"
vars = { NODE_ENV = "development" }

[[env.dev.d1_databases]]
binding = "DB"
database_name = "prompt-producer-db"
database_id = "25529814-a997-41b9-95d3-ecb453f49fbf"

[[env.dev.kv_namespaces]]
binding = "PROMPT_PRODUCER_KV"
id = "563c2211b8144bf29c2367309174dbe6"
preview_id = "386404046e2548ff8d7208062c14fa5a"

# For production
[env.production]
name = "prompt-producer-prod"
vars = { NODE_ENV = "production" }

# Production domain routes
routes = [
  { pattern = "promptproducer.me/*", zone_name = "promptproducer.me" },
  { pattern = "www.promptproducer.me/*", zone_name = "promptproducer.me" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "prompt-producer-db"
database_id = "25529814-a997-41b9-95d3-ecb453f49fbf"

[[env.production.kv_namespaces]]
binding = "PROMPT_PRODUCER_KV"
id = "563c2211b8144bf29c2367309174dbe6"
preview_id = "386404046e2548ff8d7208062c14fa5a"