name = "prompt-producer"
main = "dist/spa-worker.js"
compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist/public"

[build]
command = "npm run build:client && npm run build:spa-worker"

[vars]
NODE_ENV = "production"

[observability.logs]
enabled = true

# Add environment variables here
# DATABASE_URL will be set as a secret
# SESSION_SECRET will be set as a secret
# NEWS_API_KEY will be set as a secret

# Custom domain routes are now handled by the [site] config and Cloudflare dashboard
# routes = [
#   { pattern = "promptproducer.me/*", zone_name = "promptproducer.me" },
#   { pattern = "www.promptproducer.me/*", zone_name = "promptproducer.me" }
# ]

[[d1_databases]]
binding = "DB"
database_name = "prompt-producer-db"
database_id = "25529814-a997-41b9-95d3-ecb453f49fbf"

[[kv_namespaces]]
binding = "PROMPT_PRODUCER_KV"
id = "563c2211b8144bf29c2367309174dbe6"
preview_id = "386404046e2548ff8d7208062c14fa5a"

# For local development
[env.dev]
name = "prompt-producer-dev"
vars = { NODE_ENV = "development" }

[[env.dev.d1_databases]]
binding = "DB"
database_name = "prompt-producer-db"
database_id = "25529814-a997-41b9-95d3-ecb453f49fbf"

[[env.dev.kv_namespaces]]
binding = "PROMPT_PRODUCER_KV"
id = "563c2211b8144bf29c2367309174dbe6"
preview_id = "386404046e2548ff8d7208062c14fa5a"

# For production
[env.production]
name = "prompt-producer-prod"
vars = { NODE_ENV = "production" }

# Production domain routes are now handled by the [site] config and Cloudflare dashboard
# routes = [
#   { pattern = "promptproducer.me/*", zone_name = "promptproducer.me" },
#   { pattern = "www.promptproducer.me/*", zone_name = "promptproducer.me" }
# ]

[[env.production.d1_databases]]
binding = "DB"
database_name = "prompt-producer-db"
database_id = "25529814-a997-41b9-95d3-ecb453f49fbf"

[[env.production.kv_namespaces]]
binding = "PROMPT_PRODUCER_KV"
id = "563c2211b8144bf29c2367309174dbe6"
preview_id = "386404046e2548ff8d7208062c14fa5a"